### PR TITLE
Add audio/video conversions

### PR DESCRIPTION
**Pull request by shawnmaten**
https://filestack.atlassian.net/browse/FS-1086

Example Usage:
```java
private void videoConvert(final FileLink fileLink) {

  AvTransformOptions options = new AvTransformOptions.Builder()
      .preset("mp4")
      .width(540)
      .build();

  final AvTransform transform = fileLink.avTransform(options);

  Single.fromCallable(new Callable<FileLink>() {
    @Override
    public FileLink call() throws Exception {
      FileLink converted = null;
      while (converted == null) {
        converted = transform.getFilelink();
        if (converted == null)
          Thread.sleep(5 * 1000);
      }
      return converted;
    }
  })
      .subscribeOn(Schedulers.io())
      .observeOn(AndroidSchedulers.mainThread())
      .subscribe(new SingleObserver<FileLink>() {
        @Override
        public void onSubscribe(@NonNull Disposable d) {

        }

        @Override
        public void onSuccess(@NonNull FileLink fileLink) {
          String url = "https://cdn.filestackcontent.com/"
              + fileLink.getHandle()
              + "?policy=" + security.getPolicy()
              + "&signature=" + security.getSignature();
          textView.append(url + "\n");
          textView.append("AV TRANSFORM FINISHED\n");
        }

        @Override
        public void onError(@NonNull Throwable e) {
          textView.append("AV TRANSFORM ERROR\n");
          e.printStackTrace();
        }
      });
}
```

### CODE REVIEW

**Comment by shawnmaten** [comment]
Updated Usage Example:
```java
private void videoConvert(FileLink fileLink) {
    AvTransformOptions options = new AvTransformOptions.Builder()
            .preset("mp4")
            .height(720)
            .build();

    AvTransform transform = fileLink.avTransform(options);

    transform.getFilelinkAsync()
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new SingleObserver<FileLink>() {
                @Override
                public void onSubscribe(@NonNull Disposable d) {

                }

                @Override
                public void onSuccess(@NonNull FileLink fileLink) {
                    String url = "https://cdn.filestackcontent.com/"
                            + fileLink.getHandle()
                            + "?policy=" + security.getPolicy()
                            + "&signature=" + security.getSignature();
                    textView.append(url + "\n");
                    textView.append("AV TRANSFORM FINISHED\n");
                }

                @Override
                public void onError(@NonNull Throwable e) {
                    textView.append("AV TRANSFORM ERROR\n");
                    e.printStackTrace();
                }
            });
}
```

**Comment by kyuss** [comment]
Does the javadoc update come with this PR?

**Comment by shawnmaten** [comment]
No I was going to update the docs folder as part of the release branch. Seems cleaner to change that with releases rather than each PR. What do you think?

**Comment by kyuss** [comment]
Ok. That makes sense.

**Pull request merged**
